{"componentChunkName":"component---src-templates-tags-js","path":"/tags/git/","result":{"data":{"site":{"siteMetadata":{"title":"ij.Log"}},"allMarkdownRemark":{"totalCount":4,"edges":[{"node":{"excerpt":": remote-name","fields":{"slug":"/pages/delete-remote-branch"},"frontmatter":{"tags":["Git"],"title":"git 브랜치 삭제 (delete remote branch)","date":"2020-12-03"}}},{"node":{"excerpt":"문제 상황 git push를 하던중에 오류가 발생하며 push 를 실패하였다. 해결 1. origin 이 설정되었는지 확인 해당 명령어를 실행하면 프로젝트의 모든 push/fetch remote…","fields":{"slug":"/pages/2020-10-29-git-push-error"},"frontmatter":{"tags":["error","Git"],"title":"[Git error] fatal: 'origin' dose not appear to be a git repository","date":"2020-10-29"}}},{"node":{"excerpt":"문제 상황  명령어 실행시 아래와 같은 오류 발생  해결 방법 강제로 를 진행하였다. reference https://stackoverflow.com/questions/24414854/git-push-error-rejected-develop…","fields":{"slug":"/pages/2020-10-15-rejected-failed-to-push-some-refs"},"frontmatter":{"tags":["Git","error"],"title":"[Git error] ![rejected] Note about fast-forwards","date":"2020-10-15"}}},{"node":{"excerpt":"문제 상황  명령어 실행시 아래와 같은 오류 발생  해결 방법  대신  명령어를 실행 원인 저장소를 복제  한 후에 자신의 원격 서버를 추가하려고 할 때 해당 오류가 발생 저장소를 복제했을 때 Remote…","fields":{"slug":"/pages/2020-10-13-remote-origin-already-exists"},"frontmatter":{"tags":["Git","error"],"title":"[Git Error] Remote origin already exists","date":"2020-10-13"}}}]}},"pageContext":{"tag":"Git"}},"staticQueryHashes":["1073894666","694178885"]}